Dev
RobertIndie/moss pull request #27
Opened 2019-11-04 06:14 UTC by YHTB

Lack of testing and optimization

2019-11-04 06:48 UTC, RobertIndie commented on src/convert.cc
> +//获取一个字段的长度 单位是byte
Should have a space between // and comment  [whitespace/comments]cpplint

2019-11-04 06:49 UTC, RobertIndie commented on src/convert.cc
> +}
Please add a newline character at the end of the file.

2019-11-04 07:07 UTC, RobertIndie commented on src/convert.cc
> +inline uint8_t GetFlag(const char *const bin, const uint bits = 62) {
Remove this unused function

2019-11-04 07:16 UTC, RobertIndie commented on src/convert.cc
> +void MergeData(const char OrginData[], char DirData[], uint *location,
variable names must be lowercase with underscore.
Note that DirData name is wrong, use dest_data instead.
like:
```cpp
void MergeData(const char origin_data[], char dest_data[], uint *location, uint len)

```

2019-11-04 07:18 UTC, RobertIndie commented on src/convert.cc
> +struct tmpInfo {
> Type names start with a capital letter and have a capital letter for each new word, with no underscores. -- Google C++ Style

like: TmpInfo

2019-11-04 07:42 UTC, RobertIndie commented on src/convert.cc
> +  uint total_len = Id_len + Er_len + Fi_len;
vint does not contain flag

2019-11-04 07:46 UTC, RobertIndie commented on src/convert.cc
> +void FrsToGFL(FrameResetStream *Data, GenericFrameLayout *result) {
Abbreviated name must be all capital.
like: FRSToGFL

2019-11-04 07:53 UTC, RobertIndie requested changes
Please fix and test convert.cc

2019-11-08 02:16 UTC, RobertIndie requested changes
Compile Error. Please fix it.

2019-11-08 05:13 UTC, RobertIndie requested changes

2019-11-08 05:13 UTC, RobertIndie commented on src/convert.cc
> +uint8_t GetFlag(uint DataLen) {
use vint, not uint

2019-11-08 05:13 UTC, RobertIndie commented on src/convert.cc
> +}
Not in the correct range.

2Bit | Length | Usable Bits | Range
-- | -- | -- | --
00 | 1 | 6 | 0-63
01 | 2 | 14 | 0-16383
10 | 4 | 30 | 0-1073741823
11 | 8 | 62 | 0-4611686018427387903

2019-11-08 05:13 UTC, RobertIndie commented on src/convert.cc
> +}
Bug

2019-11-09 02:07 UTC, YHTB commented on src/convert.cc
> +uint8_t GetFlag(uint DataLen) {
Done

2019-11-09 08:04 UTC, merged